# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15V1oJZkmM-h4vWXs3p0GOB8yZC2YKy1O
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import os

# Crear carpeta de documentos si no existe
os.makedirs("documentos", exist_ok=True)

st.set_page_config(page_title="Formulario de Matrícula", layout="centered")
st.title("📄 Formulario de Matrícula Preescolar")

st.markdown("Por favor diligencia todos los campos y adjunta los documentos obligatorios.")

with st.form("formulario"):
    st.subheader("🧒 A. Información del Estudiante")
    nombre_est = st.text_input("Nombres completos del estudiante")
    apellido_est = st.text_input("Apellidos completos del estudiante")
    tipo_doc_est = st.selectbox("Tipo de documento", ["RC", "TI", "CE"])
    num_doc_est = st.text_input("Número de documento")
    fecha_nac = st.date_input("Fecha de nacimiento")
    lugar_nac = st.text_input("Lugar de nacimiento (Ciudad / Departamento)")
    edad = st.number_input("Edad actual", min_value=3, max_value=6, step=1)
    grupo_etnico = st.selectbox("Grupo étnico", ["Indígena", "Afro", "ROM", "Otro"])
    discapacidad = st.text_input("Discapacidad o condición especial (escriba 'Ninguna' si no aplica)")
    nivel = st.selectbox("Nivel a matricular", ["Prejardín", "Jardín", "Transición"])

    st.subheader("👤 B. Información del Acudiente Principal")
    nombre_acu = st.text_input("Nombre completo del acudiente")
    parentesco = st.selectbox("Parentesco con el estudiante", ["Madre", "Padre", "Tío/a", "Abuelo/a", "Otro"])
    doc_acu = st.text_input("Tipo y número de documento del acudiente")
    tel = st.text_input("Teléfono de contacto")
    correo = st.text_input("Correo electrónico")
    direccion = st.text_input("Dirección de residencia")
    barrio = st.text_input("Barrio o vereda")
    estrato = st.selectbox("Estrato socioeconómico", ["1", "2", "3", "4", "5", "6"])
    vive_junto = st.radio("¿Vive con el estudiante?", ["Sí", "No"])

    st.subheader("📎 C. Documentos obligatorios")
    doc_rc = st.file_uploader("Registro civil del estudiante", type=["pdf", "jpg", "png"])
    doc_cedula = st.file_uploader("Cédula del acudiente", type=["pdf", "jpg", "png"])
    doc_eps = st.file_uploader("Certificado de EPS o Sisbén", type=["pdf", "jpg", "png"])
    doc_vac = st.file_uploader("Certificado de vacunación", type=["pdf", "jpg", "png"])
    doc_recibo = st.file_uploader("Recibo de servicio público", type=["pdf", "jpg", "png"])
    doc_adicional = st.file_uploader("Certificado adicional (grupo étnico / discapacidad / custodia)", type=["pdf", "jpg", "png"])

    enviado = st.form_submit_button("✅ Enviar inscripción")

    if enviado:
        # Crear identificador único por estudiante
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        doc_id = f"{nombre_est}_{apellido_est}_{num_doc_est}_{timestamp}".replace(" ", "_")

        # Función para guardar y devolver el nombre del archivo
        def guardar_doc(file, nombre):
            if file:
                ext = file.name.split(".")[-1]
                archivo = f"{doc_id}_{nombre}.{ext}"
                path = os.path.join("documentos", archivo)
                with open(path, "wb") as f:
                    f.write(file.read())
                return archivo
            return ""

        archivo_rc = guardar_doc(doc_rc, "registro_civil")
        archivo_cedula = guardar_doc(doc_cedula, "cedula_acudiente")
        archivo_eps = guardar_doc(doc_eps, "eps")
        archivo_vac = guardar_doc(doc_vac, "vacunacion")
        archivo_recibo = guardar_doc(doc_recibo, "recibo")
        archivo_adicional = guardar_doc(doc_adicional, "adicional")

        # Guardar info general y nombres de archivos en Excel
        data = {
            "Fecha": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Nombre estudiante": nombre_est,
            "Apellido estudiante": apellido_est,
            "Tipo doc": tipo_doc_est,
            "N° doc": num_doc_est,
            "Fecha nacimiento": fecha_nac,
            "Lugar nacimiento": lugar_nac,
            "Edad": edad,
            "Grupo étnico": grupo_etnico,
            "Condición especial": discapacidad,
            "Nivel": nivel,
            "Nombre acudiente": nombre_acu,
            "Parentesco": parentesco,
            "Doc acudiente": doc_acu,
            "Teléfono": tel,
            "Correo": correo,
            "Dirección": direccion,
            "Barrio/vereda": barrio,
            "Estrato": estrato,
            "Vive con estudiante": vive_junto,
            "Archivo RC": archivo_rc,
            "Archivo EPS": archivo_eps,
            "Archivo Cédula": archivo_cedula,
            "Archivo Vacunación": archivo_vac,
            "Archivo Recibo": archivo_recibo,
            "Archivo Adicional": archivo_adicional
        }

        # Guardar en Excel
        archivo_excel = "encuestas.xlsx"
        try:
            df_existente = pd.read_excel(archivo_excel)
            df_nuevo = pd.concat([df_existente, pd.DataFrame([data])], ignore_index=True)
        except FileNotFoundError:
            df_nuevo = pd.DataFrame([data])

        df_nuevo.to_excel(archivo_excel, index=False)

        st.success("✅ Inscripción enviada y documentos guardados exitosamente.")